# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: START
      run: echo START

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: curl -sSL https://get.docker.com | sh
    
    - name: Install docker-compose
      run: curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      
    - name: Docker-compose chmod
      run: chmod +x /usr/local/bin/docker-compose

    - name: Clone Tiebaproject
      run: git clone https://github.com/ghosx/TiebaProject.git && cd TiebaProject
    
    - name: Run 
      run: docker-compose up
    
    - name: Stop
      run: docker-compose stop
    
    - name: END
      run: END
